#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Running lint..."
npm run lint
status_lint=$?
if [ $status_lint -ne 0 ]; then
  echo "❌ Push cancelled: Linting failed."
  exit 1
fi

echo "🧪 Running tests..."
npm test
status_test=$?
if [ $status_test -ne 0 ]; then
  echo "❌ Push cancelled: Tests failed."
  exit 1
fi

echo "✅ Lint and tests passed! Proceeding with push."
